name: trailbase
description: Thing client library for TrailBase.
homepage: https://trailbase.io
repository: https://github.com/trailbaseio/trailbase
version: 0.4.0

environment:
  sdk: ^3.6.1
resolution: workspace

dependencies:
  crypto: ^3.0.6
  dio: ^5.8.0+1
  jwt_decoder: ^2.0.1
  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
